name: fca
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - blas=1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - certifi=2023.11.17
  - cffi=1.16.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - cryptography=41.0.7
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cytoolz=0.12.2
  - dask-core=2023.11.0
  - dav1d=1.2.1
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - fsspec=2023.10.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.31.4
  - importlib-metadata=6.0.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jxrlib=1.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcurand=10.3.4.101
  - libcurl=8.4.0
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.26.2
  - numpy-base=1.26.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.12
  - partd=1.4.1
  - pillow=10.0.1
  - pip=23.3.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.9.18
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - scikit-image=0.19.3
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - setuptools=68.2.2
  - snappy=1.1.9
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tifffile=2023.2.28
  - tk=8.6.12
  - toolz=0.12.0
  - torchaudio=2.1.2
  - torchtriton=2.1.0
  - torchvision=0.16.2
  - tqdm=4.66.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zfp=1.0.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - antlr4-python3-runtime==4.9.3
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - opencv-python==4.8.1.78
    - packaging==23.2
